import { useEffect, useState } from 'react';
const api = path => fetch(path).then(async r => { const d = await r.json(); if (!r.ok) throw Error(d.detail); return d; });
export default function SquadBuilder() {
  const [seasons,setSeasons]=useState([]),[season,setSeason]=useState(''),[teams,setTeams]=useState([]),[team,setTeam]=useState(''),[data,setData]=useState(null),[error,setError]=useState('');
  useEffect(()=>{api('/api/seasons').then(x=>{setSeasons(x);setSeason(x.includes('2025')?'2025':x[0]);}).catch(e=>setError(e.message));},[]);
  useEffect(()=>{if(season) api(`/api/teams?season=${encodeURIComponent(season)}`).then(x=>{setTeams(x);setTeam(x[0]||'');}).catch(e=>setError(e.message));},[season]);
  useEffect(()=>{if(team&&season){setData(null);api(`/api/squad/${encodeURIComponent(team)}?season=${encodeURIComponent(season)}`).then(setData).catch(e=>setError(e.message));}},[team,season]);
  return <div><div className="flex flex-col md:flex-row justify-between gap-4 mb-8"><div><h2 className="text-3xl font-bold mb-2">Season Squad Builder</h2><p className="text-slate-400">Real players, roles, stability and SWOT for one IPL season.</p></div><div className="flex gap-3"><Select value={season} change={setSeason} items={seasons}/><Select value={team} change={setTeam} items={teams}/></div></div>{error&&<p className="text-red-300">{error}</p>}{!data&&!error?<p className="text-slate-400">Calculating the selected season…</p>:data&&<><div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6"><section className="bg-slate-900/50 p-5 rounded-2xl border border-slate-700"><p className="text-slate-400">Stability score</p><p className="text-5xl font-black text-blue-400">{data.stability_score}</p><p className="text-xs text-slate-500 mt-2">{data.score_method}</p></section><section className="md:col-span-2 bg-slate-900/50 p-5 rounded-2xl border border-slate-700"><h3 className="font-semibold mb-2">Role balance</h3><p className="text-slate-300">{data.role_counts.Batter} batters · {data.role_counts['All-rounder']} all-rounders · {data.role_counts.Bowler} bowlers</p><ul className="list-disc pl-5 text-sm text-slate-400 mt-3">{data.notes.map(x=><li key={x}>{x}</li>)}</ul></section></div><section className="bg-slate-900/50 p-5 rounded-2xl border border-slate-700 mb-6"><h3 className="font-semibold mb-3">Dynamic SWOT report</h3><div className="grid md:grid-cols-2 gap-3 text-sm"><Item tag="Strength" text={data.swot.strength}/><Item tag="Weakness" text={data.swot.weakness}/><Item tag="Opportunity" text={data.swot.opportunity}/><Item tag="Threat" text={data.swot.threat}/></div></section><Table players={data.players}/></>}</div>;
}
function Select({value,change,items}){return <select value={value} onChange={e=>change(e.target.value)} className="bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-white">{items.map(x=><option key={x}>{x}</option>)}</select>}
function Item({tag,text}){return <div className="border border-slate-800 rounded-lg p-3"><b className="text-blue-300">{tag}: </b>{text}</div>}
function Table({players}){return <div className="overflow-x-auto"><table className="w-full text-left"><thead className="text-slate-400 text-sm border-b border-slate-700"><tr><th className="p-3">Player</th><th className="p-3">Role</th><th className="p-3 text-right">Runs</th><th className="p-3 text-right">Bat SR</th><th className="p-3 text-right">Wickets</th><th className="p-3 text-right">Economy</th></tr></thead><tbody>{players.map(p=><tr key={p.player} className="border-b border-slate-800"><td className="p-3 font-medium">{p.player}</td><td className="p-3">{p.role}</td><td className="p-3 text-right">{p.runs} <span className="text-xs text-slate-500">({p.batting_balls}b)</span></td><td className="p-3 text-right">{p.strike_rate}</td><td className="p-3 text-right">{p.wickets}</td><td className="p-3 text-right">{p.bowling_balls?p.economy:'—'}</td></tr>)}</tbody></table></div>}
